channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - dataclasses
  - numpy
  - scipy
  - audioread
  - nwani::portaudio
  - nwani::pyaudio
  - lark-parser
  - wcwidth
  - psutil
  - appdirs
  - twine
